### PR TITLE
Fix 3.1.0 upgrade problems, restore and enhance serialization prefs

### LINKED ISSUE #333: [BUG] Restore dbutil module, formerly supplied by shared-resources
**Describe the bug**

Loading eXide 3.0.0 on a stock eXist 5.3.0 system produces a console error when eXide calls this URL:

```
http://localhost:8080/exist/apps/eXide/modules/deployment.xql?info=__new__1
```

The error:

```xml
<exception>
    <path>/db/apps/eXide/modules/deployment.xql</path>
    <message>err:XQST0059 error found while loading module dbutil: failed to load module:
        'http://exist-db.org/xquery/dbutil' from: 'http://exist-db.org/xquery/dbutil', location:
        'http://exist-db.org/xquery/dbutil'. Source not found. </message>
</exception>
```

The cause is that #309 removed the declared dependency on shared-resources but left a reference to it in `deployment.xql` and `search.xql`.

Until this module is released in a standalone package, the shortest path to a solution may be to embed the library module in eXide.

### PR DESCRIPTION
**Pull request by joewiz**
Fixes issues introduced in the eXide 3.1.0 release by #328.

Adds fine-grained serialization preferences:

> Screen Shot 2021-11-21 at 4 37 10 PM

Closes #333 and #334.

### CODE REVIEW

**Comment by joewiz** [comment]
@wolfgangmm Thanks for your help on today's Community Call! I tried integrating your suggestions—in https://github.com/eXist-db/eXide/pull/335/commits/ced6868a8291939f13966bf76094f0ac98429115. But, as my comment in preferences.js line 40 states, the addition of `eXide.app.version()` raised this error in the console:

> Uncaught TypeError: Cannot read property 'version' of undefined

This is strange, because the same expression can be found elsewhere in preferences.js. Do you have any suggestions for dynamically registering the version?

**Comment by joewiz** [comment]
Note that once #374 is merged, the feature commit in #328 will need to be re-added to this branch so that work on the fix started here can proceed.

File: src/preferences.js [hunk 1]
```diff
@@ -173,7 +174,7 @@ eXide.util.Preferences = (function () {
     Constr.prototype.read = function() {
         var sameVersion = false;
         if (localStorage["eXide.preferences"]) {
-            this.preferences = JSON.parse(localStorage.getItem("eXide.preferences"));
+            this.preferences = Object.assign(defaultPreferences, JSON.parse(localStorage.getItem("eXide.preferences")));
```
Comment (wolfgangmm) [inline src/preferences.js]: This line should be changed as follows or the defaultPreferences would be overwritten:

```javascript
const loaded = JSON.parse(localStorage.getItem("eXide.preferences"));
this.preferences = Object.assign({}, defaultPreferences, loaded);
```

**Review by wolfgangmm — CHANGES_REQUESTED** [review]
See my inline comment.

File: src/preferences.js (hunk 1 above)
Comment (wolfgangmm) [reply src/preferences.js]: I tested above change on my local eXide install and it works as expected.

File: index.html.tmpl [hunk 2]
```diff
@@ -683,6 +685,45 @@
...
+                        <fieldset>
+                            <legend>Serialization</legend>
+                            <p>Control (a) whether indentation is applied to XML documents or not
+                                and (b) whether XInclude elements are expanded, when opening or
+                                downloading resources and EXPath packages.</p>
+                            <h3>Opening files (via File > Open)</h3>
+                            <ol>
+                                <li>
+                                    <label for="indent-on-open">Indent:</label>
+                                    <input type="checkbox" name="indent-on-load" id="indent-on-open"/>
```
Comment (wolfgangmm) [inline index.html.tmpl]: Above needs to be changed to `name="indent-on-open"` for the setting to be picked up correctly.

File: src/preferences.js [hunk 3]
```diff
@@ -167,8 +186,8 @@ eXide.util.Preferences = (function () {
     Constr.prototype.read = function() {
         var sameVersion = false;
         if (localStorage["eXide.preferences"]) {
-            this.preferences = JSON.parse(localStorage.getItem("eXide.preferences"));
-            sameVersion = (this.preferences.version === eXide.app.version());
+            const loaded = JSON.parse(localStorage.getItem("eXide.preferences"));
+            this.preferences = Object.assign({}, defaultPreferences, loaded);
         }
 
         this.preferences.version = eXide.app.version();
```
Comment (wolfgangmm) [inline src/preferences.js:201]: Add `this.updateForm();` after `this.applyPreferences();` for the UI form to be updated.

File: index.html.tmpl (hunk 2 above)
Comment (joewiz) [reply index.html.tmpl]: @wolfgangmm Ugh, thank you for catching this! I thought I'd caught them all.

File: src/preferences.js (hunk 3 above)
Comment (joewiz) [reply src/preferences.js:201]: @wolfgangmm `this.applyPreferences();` appears twice in preferences.js: first in `Constr.prototype.updatePreferences` (line 145) and second in `Constr.prototype.read` (line 195). Should I apply your suggested change to both instances?

Comment (wolfgangmm) [reply src/preferences.js:201]: @joewiz it should only be applied to `Constr.prototype.read`.

File: index.html.tmpl (hunk 2 above)
Comment (joewiz) [reply index.html.tmpl]: Fixed in latest force-pushed commits.

File: src/preferences.js (hunk 3 above)
Comment (joewiz) [reply src/preferences.js:201]: @wolfgangmm Thank you! I've applied this change to the latest force-pushed commits. It works perfectly in my testing. Prefs are picked up without a shift-reload; a simple reload when uploading does the trick.

**Review by wolfgangmm — APPROVED** [review]

**Comment by joewiz** [comment]
@wolfgangmm Many thanks!
